### ISSUE TITLE
Path to Stage 4

### ISSUE THREAD

**Issue by erights** [Agoric/proposal-stabilize#2]
## Stage 4
* [ ]  committee approval
* [ ]  two implementations
  * [ ]  JavaScriptCore
  * [ ]  SpiderMonkey
  * [ ]  XS
  * [ ]  V8
* [ ]  significant in-the-field experience
* [ ]  ecma262 PR approved
* [ ]  prepare ecma262 PR

## Stage 3
* [ ] merge test262 tests
* [ ] write test262 tests
* [ ] receive implementer feedback

## Stage 2.7
* [ ]  committee approval
* [ ]  spec editor signoff
* [ ]  spec reviewer signoff
* [ ]  resolve all normative [issues](../issues)
* [ ]  receive implementer feedback
  * [x] [shim of non-trapping integrity trait #2637](https://github.com/endojs/endo/pull/2673) supports the non-trapping trait, which is the only one that can practically be shimmed. Its [practical use #2675](https://github.com/endojs/endo/pull/2675) illuminates issues in practically using this shim for safety.
  * [ ] others...?

## Stage 2
* [ ]  committee approval
* [ ]  spec reviewers selected
* [ ]  spec text written

## ~Stage 1~
* [x]  committee approval
